# Generated by Django 5.0 on 2024-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0004_customer_first_name_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
