# Generated by Django 5.0 on 2024-08-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0008_customer_address2_customer_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
    ]
