# Generated by Django 5.0 on 2024-08-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0009_remove_customer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
